### ISSUE TITLE
Interleaved 2 of 5

### ISSUE THREAD

**Issue by jozef-pridavok** [DavBfr/dart_barcode#14]
Do you plan to implement support for Interleaved 2 of 5 (https://en.wikipedia.org/wiki/Interleaved_2_of_5)? It would be great to have support for it in your package...

**Comment by DavBfr** [comment]
There you are: barcode version 1.13.0 includes it. It's `Barcode.itf()`.

Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h)!
