### ISSUE TITLE
Can't scan QR

### ISSUE THREAD

**Issue by purushottamyadavbattula** [DavBfr/dart_barcode#15]
can't scan QR when kept into a card with background color ?? (Flutter)
![Screenshot 2020-06-25 at 5 32 43 AM](https://user-images.githubusercontent.com/30764017/85639100-54fdce00-b6a5-11ea-85a3-d5a79a984f84.png)

**Comment by DavBfr** [comment]
You need a white or light color margin around the QRCode in order to make it readable. Otherwise the reader can't find the beginning of the matrix.

**Comment by purushottamyadavbattula** [comment]
Still not working I added the margin
![Screenshot 2020-06-25 at 5 52 04 AM](https://user-images.githubusercontent.com/30764017/85640070-6399b480-b6a8-11ea-9c3a-2c25593c9a41.png)
![Screenshot 2020-06-25 at 5 55 27 AM](https://user-images.githubusercontent.com/30764017/85640137-98a60700-b6a8-11ea-8a65-8360d7aabbbc.png)

**Comment by DavBfr** [comment]
You inversed the colors? The readers expect the small squares in the 3 corners to be filled black. You can't change the colors. https://en.wikipedia.org/wiki/QR_code

**Comment by purushottamyadavbattula** [comment]
No, I am not inversing any colors,
`
Container(
color: Colors.black,
Container(
                    decoration: BoxDecoration(
                      border: Border.all(color: Colors.white),
                    ),
                    child: BarcodeWidget(
                      color: Colors.white,
                      height: 100,
                      width: 100,
                      barcode: Barcode.qrCode(),
                      data: 'https"//csedata-cdb17.firebaseapp.com',
                    ),
                  ),
),`

**Comment by purushottamyadavbattula** [comment]
Wow working now, I think I have to inverse and nullify the background colors, Thank for the article and quick response (appreciated)
![Screenshot 2020-06-25 at 7 39 34 AM](https://user-images.githubusercontent.com/30764017/85645382-2f79c000-b6b7-11ea-964f-7eecc4053eb9.png)
`Container( color:black,Container(
                    decoration: BoxDecoration(
                      border: Border.all(color: Colors.white),
                    ),
                    child: Container(
                      color: Colors.white,
                      child: BarcodeWidget(
                        color: Colors.black,
                        height: 100,
                        width: 100,
                        barcode: Barcode.qrCode(),
                        data: link, //'https"//csedata-cdb17.firebaseapp.com',
                      ),
                    ),
                  ),),`

**Comment by Leoudayan** [comment]
Can you post the code for the scan? I can only see the code for generation but not scanning :(

**Comment by DavBfr** [comment]
@Leoudayan This plugin can only create barcodes, not scan them.
