### ISSUE TITLE
Error to generate barcode

### ISSUE THREAD

**Issue by luissouza** [DavBfr/dart_barcode#16]
Im using this code to generate barcode:

`final image = Image(300, 150);

 fill(image, getColor(255, 255, 255));

 drawBarcode(image, Barcode.ean13(), "1064992311055.svg ", font: arial_24);`

**And I got this error:**

type '() => (_SyncIterator< BarcodeText >) => bool' is not a subtype of type '() =>
(_SyncIterator< BarcodeElement >) => bool'

What I did wrong? Im using **barcode_image** version **1.0.3** and my flutter sdk is **1.20.0-2.0.pre**

**Comment by luissouza** [comment]
I downgrade version 1.20.0-2.0.pre(dev) to Flutter 1.17.5 (stable) and it works now!

**Comment by DavBfr** [comment]
I pushed a new version 1.1.0 that works with Flutter 1.20.0
