### ISSUE TITLE
unable to encode CodaBar 

### ISSUE THREAD

**Issue by kw2019ltd** [DavBfr/dart_barcode#17]
hi,
my CodaBar is **A123456789B** this is rawValue , and when trying to build widget its failing ,

can you handle it to check if its already having start and end BarcodeCodabarStartStop.

![1595599330350](https://user-images.githubusercontent.com/47334522/88400066-70591780-cdd0-11ea-8a58-e7616e9dbccc.jpg)
![screenshot_20200724-170456](https://user-images.githubusercontent.com/47334522/88400070-718a4480-cdd0-11ea-94a1-8dfbe41beff7.jpg)

**Comment by kw2019ltd** [comment]
example if i want to display something like this , it will not work as you dont expect for "data" to be "A23342453D" 
BarcodeWidget({
    @required String data

![image](https://user-images.githubusercontent.com/47334522/88404834-17d94880-cdd7-11ea-88f8-8e9f2be38bb5.png)

**Comment by kw2019ltd** [comment]
getting many issue like below even barcode is valid

![image](https://user-images.githubusercontent.com/47334522/88451316-5cf48d80-ce5e-11ea-85ca-c460a9fb9673.png)

**Comment by DavBfr** [comment]
Actually, you can adapt your code to make it work: It's already possible to specify the Start and Stop values (A, B, C, or D)

You can create a function to convert your string "A123456789D" to:

```dart
BarcodeWidget(
            data: '123456789',
            width: 60,
            height: 60,
            barcode: Barcode.codabar(
                  start = BarcodeCodabarStartStop.A,
                  stop = BarcodeCodabarStartStop.D,
            ),
),
```

**Comment by kw2019ltd** [comment]
Hi, in my case data is  A123456789B

So i need to remove start and end chars, and to specify start and end
barcode Type. Can't this be done inside plugin?

Also in case iam doing a WA by removing start and end chars,

BarCodeWidget dose not display start and end, it only display number

**Comment by kw2019ltd** [comment]
i did the WA but the BarcodeWidget dose not display the start and the end

![1595750015850](https://user-images.githubusercontent.com/47334522/88474428-04d98c00-cf2f-11ea-90ec-4ebeec87bf42.jpg)

**Comment by DavBfr** [comment]
I can add an option to display the start and stop chars. Would that work?

**Comment by kw2019ltd** [comment]
Hi yes it will be helpful

**Comment by DavBfr** [comment]
Actually, I'll add 2 switches:

- **printStartStop**: Outputs the Start and Stop characters as text under the barcode
- **explicitStartStop**: The caller must explicitly specify the Start and Stop characters as letters (ABCDETN*) in the data. In this case, start and stop settings are ignored

For your use-case, you'll want both to be set to true.

**Comment by kw2019ltd** [comment]
Yes excellent.

**Comment by DavBfr** [comment]
I just pushed the fix, can you test the master branch?

**Comment by kw2019ltd** [comment]
hi tested looks good 

![screenshot_20200728-120257](https://user-images.githubusercontent.com/47334522/88643476-684bf100-d0ca-11ea-8f3d-5d7eb7b7e882.jpg)

**Comment by kw2019ltd** [comment]
hi when you planing to release new version ?

**Comment by DavBfr** [comment]
There you go!
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
