### ISSUE TITLE
expose method to return text with calculated checksum

### ISSUE THREAD

**Issue by kw2019ltd** [DavBfr/dart_barcode#19]
Hi,
can you expose method for ITF/EAN/UPC codes,    input is barcode text and return barcode text + (checksum) if input text dose not contain checksum.

**Comment by DavBfr** [comment]
A version with this is available in the master branch.

use:
```dart
    final BarcodeEan ean13 = Barcode.ean13();
    final value = ean13.normalize('453987234345');
```

**Comment by kw2019ltd** [comment]
tested all fine except upce , example try to normalize 1234567  result should be 12345670  but failing with

print(Barcode.upcE().isValid("1234567")) -> print true
print(barcodeEan.normalize("1234567")) - > failing below

BarcodeException: Unable to convert "1234567" to UPC E Barcode
I/flutter ( 6015): SEVERE: 2020-08-17 13:41:59.180170: #0      BarcodeUpcE.upcaToUpce (package:barcode/src/upce.dart:79:7)
I/flutter ( 6015): #1      BarcodeUpcE.normalize (package:barcode/src/upce.dart:370:14)
I/flutter ( 6015): #2      _EanTextEditingControllerWidgetState._createManualBarcodeDto (package:barcodeapp/widget/qr_barcode/create/ean_widget.dart:264:22)
I/flutter ( 6015): #3      _EanTextEditingControllerWidgetState._onPressed (package:barcodeapp/widget/qr_barcode/create/ean_widget.dart:222:19)
I/flutter ( 6015): #4      _EanTextEditingControllerWidgetState.build.<anonymous closure> (package:barcodeapp/widget/qr_barcode/create/ean_widget.dart:177:31)

**Comment by kw2019ltd** [comment]
another example: 987456  when normalize it should be 09874565

print(Barcode.upcE().isValid("987456")) -> print true
print(barcodeEan.normalize("987456")) - > failing below

**Comment by DavBfr** [comment]
Yes, you have to use the fallback:

```dart
print(Barcode.upcE(fallback: true).isValid("987456"))
```

**Comment by kw2019ltd** [comment]
i think iam missing something, for UPCE
the code is 555555, and isValid return true.

now in barCodeWidget it display it as 05555550

but barcodeEan.normalize("555555") is failing on ,  why its not returning 05555550 ?

BarcodeException: Unable to convert "555555" to UPC E Barcode
I/flutter ( 6015): SEVERE: 2020-08-17 13:41:59.180170: #0 BarcodeUpcE.upcaToUpce (package:barcode/src/upce.dart:79:7)
I/flutter ( 6015): #1 BarcodeUpcE.normalize (package:barcode/src/upce.dart:370:14)
I/flutter ( 6015): #2 _EanTextEditingControllerWidgetState._createManualBarcodeDto (package:barcodeapp/widget/qr_barcode/create/ean_widget.dart:264:22)
I/flutter ( 6015): #3 _EanTextEditingControllerWidgetState._onPressed (package:barcodeapp/widget/qr_barcode/create/ean_widget.dart:222:19)
I/flutter ( 6015): #4 _EanTextEditingControllerWidgetState.build. (package:barcodeapp/widget/qr_barcode/create/ean_widget.dart:177:31)

**Comment by kw2019ltd** [comment]
here the code is 555555 , and barcodeWidget works fine , but barcodeEan.normalize("555555") is failing 
![Screenshot_1597766076](https://user-images.githubusercontent.com/47334522/90536101-494df580-e184-11ea-93df-c063f3f2bea0.png)

**Comment by kw2019ltd** [comment]
see also

https://online-barcode-generator.net/

![image](https://user-images.githubusercontent.com/47334522/90536888-53bcbf00-e185-11ea-81e4-d7c325b551f7.png)

**Comment by DavBfr** [comment]
@kw2019ltd Here is a fix which should work as expected now.

**Comment by kw2019ltd** [comment]
now its working fine, can you release new ver

thanks.

**Comment by DavBfr** [comment]
Done.
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by kw2019ltd** [comment]
hi you create new ver in pub?

**Comment by DavBfr** [comment]
@kw2019ltd it's already updated: https://pub.dev/packages/barcode/changelog
