### ISSUE TITLE
Is possible to generate PNG barcode or convert?

### ISSUE THREAD

**Issue by luissouza** [DavBfr/dart_barcode#2]
I just need to print in my bluetooth printer, but my printer only supports PNG.
Thks :)

**Comment by DavBfr** [comment]
https://pub.dev/packages/barcode_image
Is just for that.

**Comment by luissouza** [comment]
Tks @DavBfr!!

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
