### ISSUE TITLE
Update more barcode format type

### ISSUE THREAD

**Issue by minhduc1827** [DavBfr/dart_barcode#22]
Hello all, would you please update more barcode format type such as Rss14,...

**Comment by DavBfr** [comment]
@minhduc1827 can you finance the development of this barcode?

**Comment by minhduc1827** [comment]
I only use to check the recognization barcode and i tested with the barcode
sample on google

**Comment by vikskod** [comment]
Hello,
Is there anyway to get bitmap from it?
