### ISSUE TITLE
Optional start and end characters [A,B,C,D] for Codabar causes failure to encode error.

### ISSUE THREAD

**Issue by samir97** [DavBfr/dart_barcode#23]
The widget works fine for numeric, and special characters data. However, Codabar can optionally have [A,B,C,D] as a start or end character which encoded, adding these causes a crash.

1234-$/+. works fine.
A1234A throws an exception.

**Comment by DavBfr** [comment]
If you want to manually specify the start and stop characters, use:
```dart
Barcode.codabar(
      explicitStartStop: true,
);
```

or 

```dart
Barcode.codabar(
        start: BarcodeCodabarStartStop.B,
        stop: BarcodeCodabarStartStop.D,
);
```

**Comment by samir97** [comment]
> If you want to manually specify the start and stop characters, use:
> 
> ```dart
> Barcode.codabar(
>       explicitStartStop: true,
> );
> ```
> 
> or
> 
> ```dart
> Barcode.codabar(
>         start: BarcodeCodabarStartStop.B,
>         stop: BarcodeCodabarStartStop.D,
> );
> ```

Thank you, that fixed the issue.

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
