### ISSUE TITLE
How to add image to pdf417?

### ISSUE THREAD

**Issue by GOSSII** [DavBfr/dart_barcode#25]

**Comment by DavBfr** [comment]
What do you mean, do you have an example?

**Comment by GOSSII** [comment]
LIke US Driving license, Once you scan it will show Text and profile Picture.  

example - https://www.codeproject.com/KB/showcase/5272731/driver-license-r-700.jpg

Is it possible to store the image into the pdf417 barcode?

**Comment by DavBfr** [comment]
Yes, you can store binary data, but you have to figure out what format you need.
