### ISSUE TITLE
add support to pdf417

### ISSUE THREAD

**Issue by kw2019ltd** [DavBfr/dart_barcode#3]

**Comment by DavBfr** [comment]
Can you add more information?

- A link to the specification
- An app that I can use to scan it to validate
- why it is needed

**Comment by kw2019ltd** [comment]
in your plugin there is no option to generate barcode with Type(format)  pdf417 

https://en.wikipedia.org/wiki/PDF417

right now for pdf417/aztec/dataMatrix format i used plugin barcode_generator.

but it will be good if you added them in your plugin also.

**Comment by DavBfr** [comment]
I have no support for 2D barcodes in this library, and PDF417 is not the most interesting, except for US postal services.

**Comment by kw2019ltd** [comment]
yes but in general if you support all possible format including  pdf417/aztec/dataMatrix it will be good.

as i said for format pdf417/aztec/dataMatrix i use : barcode_generator

**Comment by DavBfr** [comment]
@kw2019ltd I implemented it in version 1.8.0 with qr-code, pdf417, data matrix and codabar.
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
