### ISSUE TITLE
add support for pretty qr code

### ISSUE THREAD

**Issue by kw2019ltd** [DavBfr/dart_barcode#30]
hi
its possible to impalement/enhance current qr code widget to support pretty qr code

where icon in middle of qr code

![image](https://user-images.githubusercontent.com/47334522/114179475-b565af80-9947-11eb-902c-2ef952e4b139.png)

![image](https://user-images.githubusercontent.com/47334522/114179529-c7475280-9947-11eb-95b8-b55711e73418.png)

**Comment by DavBfr** [comment]
You can just use a Stack() with the Barcode() and the Image() on top, it's no more than that.
