### ISSUE TITLE
Barcode UPC

### ISSUE THREAD

**Issue by ardipermana59** [DavBfr/dart_barcode#34]
in here `https://davbfr.github.io/dart_barcode/#/` when i choose `UPC A` and i input data `1` will not error.  data will be filled  100000000007 automatic. but, in flutter i wrote 
```
BarcodeWidget(
    data: '1',
   barcode: Barcode.upcA(),
),
```
will display an error.
is there a feature to generate data like on the web so there is no error?

**Comment by DavBfr** [comment]
Yes, Try like this:

```dart
final barcode = Barcode.upcA() as BarcodeEan;
final data = barcode.normalize('1');

...

BarcodeWidget(
    data: data,
   barcode: barcode,
)
```

**Comment by ardipermana59** [comment]
thank you very much

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
