### ISSUE TITLE
UPC E error

### ISSUE THREAD

**Issue by ardipermana59** [DavBfr/dart_barcode#35]
UPC E error on some data, for example I enter `7777444`.  will display an error. then i try to use `http://www.barcode-generator.org/` UPC E with same data. there is no error. What is this error, is the data not able to be generated by UPC E?

**Comment by DavBfr** [comment]
UPC-E allows the use of UPC barcodes where a full 12-digit barcode may not fit. All trailing zeros in the manufacturer code, and all leading zeros in the product code, are suppressed. So in this library, the code must be a valid 12-digits UPC-A code that can be converted to UPC-E. Or a valid 8-digits code, like 07774441. 777444 will also be accepted and will be converted to 07774441.
If you want to create non-standard barcodes with the same features, use ITF.
