### ISSUE TITLE
Add support for Telepen

### ISSUE THREAD

**Issue by samir97** [DavBfr/dart_barcode#4]
It is a continuous, variable-length, one-dimensional symbology that is designed to encode all 128 ASCII characters without using shift characters and to be highly reliable even when printed by ordinary printers that are not intended for barcode printing.  Its main use has been in university and other academic libraries in the UK.

I want to use it take attendance/verify students to clubs, societies, and events, as a unique barcode is given to each student.

You can generate it online at:
https://barcode.tec-it.com/en/TelepenAlpha

**Comment by DavBfr** [comment]
Added in barcode version 1.6.0
I think you can [Buy Me A few Coffees](https://www.buymeacoffee.com/JORBmbw9h)!
