### ISSUE TITLE
Barcode 128 wrong

### ISSUE THREAD

**Issue by SomeCodingUser** [DavBfr/dart_barcode#46]
Hi,

I tried generating a barcode generating a barcode 128 with the data '053172STB' which generates the following barcode:
![image](https://user-images.githubusercontent.com/22557413/185760516-461c1194-ef97-495d-985d-63eaf40014f6.png)

Which is wrong according to other barcode generators and also the originial barcode which I tried to scan and regenerate. The barcode should look like this:
![image](https://user-images.githubusercontent.com/22557413/185760502-11327826-6fb9-4451-9a17-9a27c7d768ee.png)

Is this because I set the parameters useCode128A, etc. wrong (I tried playing around with them but didn't help) or is there a problem with the algorithm?

**Comment by DavBfr** [comment]
Yes, it's a bug.

**Comment by DavBfr** [comment]
Fixed in master branch.

If you want the exact same code, set useCode128A=false.

Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
