### ISSUE TITLE
The generated data is incorrect

### ISSUE THREAD

**Issue by LuodiJackShen** [DavBfr/dart_barcode#47]
I chose UPC-E format, the content is 02201904, but the final generation is 02201934, I hope to repair as soon as possible, thank you!

<img width="1660" alt="截屏2022-09-23 15 09 46" src="https://user-images.githubusercontent.com/25525335/191908768-656b06ea-6cd8-44aa-9472-b4893532f9cd.png">

**Comment by LuodiJackShen** [comment]
upc-e '06503219' 
it had the same problem.

**Comment by DavBfr** [comment]
That's expected: UPC-E is designed to represent short versions of UPC-A. So you pass it an UPC-A code and the library will try to generate the UPC-E short version, and optionally fallback to the full UPC-A code if it can't.

**Comment by LuodiJackShen** [comment]
As you said, it actually provides a function to convert UPC-A to UPC-E, rather than allowing users to directly input the UPC-E code and generate the corresponding barcode. Is this misleading?

**Comment by LuodiJackShen** [comment]
We would like to see this library provide the ability to directly input the code for UPC-E and generate the corresponding barcode. Thank you very much!
