### ISSUE TITLE
Unable to encode "A" to CODABAR Barcode

### ISSUE THREAD

**Issue by pavel-vhive** [DavBfr/dart_barcode#49]
![codabar](https://user-images.githubusercontent.com/96182119/199356839-8e769865-78f2-4e15-8fea-57e02a74a42e.svg)

======== Exception caught by Barcode Widget ========================================================
The following BarcodeException was thrown:
Unable to encode "A" to CODABAR Barcode

====================================================================================================

**Comment by DavBfr** [comment]
What's the code to make this?

**Comment by karim-8** [comment]
The same error happened to me also,
This is my widget I'm trying to present

            BarcodeWidget(
              barcode: Barcode.codabar(),
              data: 'https://pub.dev/packages/barcode_widget',
              width: 250,
              height: 38,
            ),

**Comment by DavBfr** [comment]
Yes, read the article and specifications: https://en.wikipedia.org/wiki/Codabar
this barcode can only encode 0 to 9 and - $ . / : +
