### ISSUE TITLE
update dependency for barcode_widget on barcode to 1.8.0

### ISSUE THREAD

**Issue by kw2019ltd** [DavBfr/dart_barcode#5]
iam using barcode_widget: ^1.2.3  but code of barcode is not updated with latest code

**Comment by kw2019ltd** [comment]
![image](https://user-images.githubusercontent.com/47334522/80281796-66af0d80-8716-11ea-9279-6a7e3827d19e.png)

**Comment by DavBfr** [comment]
try 

```shell
flutter pub upgrade
```

**Comment by kw2019ltd** [comment]
yes working for me tnx

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
