### ISSUE TITLE
Using Barcode. code128() to generate barcodes will occasionally cause errors

### ISSUE THREAD

**Issue by IsVivian** [DavBfr/dart_barcode#51]
This is an incorrect barcode
![WeChat0031c8977782006cf666ffe9fa87f106](https://user-images.githubusercontent.com/16147457/201311542-9d542357-5732-4527-b6a7-70151fa39c35.png)
This is the correct barcode
![WeChat266d3c720a9b2756deaf7f6b8195f2b5](https://user-images.githubusercontent.com/16147457/201311633-82849355-266a-414f-9b56-0dd50f1d20e4.png)

barcode_widget: ^1.5.0
sdk: ">=2.10.0 <3.0.0"
flutter: 2.2.3

BarcodeWidget(
                              barcode: Barcode.code128(),
                              data: 'w00168mb',
                              width: 200,
                              height: 80,
                              drawText: false,
                            )

**Comment by DavBfr** [comment]
Sorry, I can't reproduce that, even with this 2-years old library version.

**Comment by mdeandrea-mrmilu** [comment]
I tried reproduced and I cant too
![Screenshot 2022-12-02 at 09 23 37](https://user-images.githubusercontent.com/98474585/205248706-536f3c21-76ae-405d-904a-86d510082cd9.png)
