### ISSUE TITLE
barcode >=2.2.0 depends on qr ^3.0 and qr_flutter >=4.0.0 depends on qr ^2.0.0

### ISSUE THREAD

**Issue by LarssK-TS** [DavBfr/dart_barcode#59]
Trying to install a two factor authentication package 
`Because barcode >=2.2.0 depends on qr ^3.0.0 and qr_flutter >=4.0.0 depends on qr ^2.0.0, barcode >=2.2.0 is incompatible with qr_flutter >=4.0.0.
And because every version of flutter_2fa depends on qr_flutter ^4.0.0, barcode >=2.2.0 is incompatible with flutter_2fa.`

Please update the packages

**Comment by DavBfr** [comment]
It would be best to ask the flutter_2fa maintainer to use barcode instead of qr_flutter. qr_flutter has not been updated in the last 2 years, it seems abandoned.

**Comment by LarssK-TS** [comment]
> It would be best to ask the flutter_2fa maintainer to use barcode instead of qr_flutter. qr_flutter has not been updated in the last 2 years, it seems abandoned.

Thank you
