### ISSUE TITLE
Save as file support

### ISSUE THREAD

**Issue by thisFemi** [DavBfr/dart_barcode#61]
Please add a feature that allow users save to any/ specified format

**Comment by DavBfr** [comment]
What do you mean?

**Comment by thisFemi** [comment]
Letting users have the option to save the barcode in the BarcodeWidget.... instead of going through the RepaintBoundary method

**Comment by DavBfr** [comment]
There is a .toSvg() method.

```dart
// Create a DataMatrix barcode
final dm = Barcode.dataMatrix();

// Generate a SVG with "Hello World!"
final svg = bc.toSvg('Hello World!', width: 200, height: 200);

// Save the image
await File('barcode.svg').writeAsString(svg);
```

**Comment by thisFemi** [comment]
Oh great, i couldn’t find it at first.
Thanks
