### ISSUE TITLE
Ean2 barcode error in v2.2.4.

### ISSUE THREAD

**Issue by shinbin** [DavBfr/dart_barcode#64]
Hello author, I would like to report that the barcode content generated by ean2 is wrong in v2.2.4 . The data content is such as "12" or "48", etc., resulting in an incorrect ean2 barcode.
I have used Scanner to scan EAN8 with EAN2 addon and other barcode tests. I also refer to the EAN2 content generated by professional barcode software or websites ( 'https://www.online-barcode.com/'). The EAN2 barcodes produced by these sources are different from v2.2.4.
Please help with the revision, 
thank you very much.
![ean2-err](https://github.com/DavBfr/dart_barcode/assets/12267647/169692a6-e9a0-4d10-b849-30cd490161f6)

**Comment by shinbin** [comment]
I refer to https://en.wikipedia.org/wiki/EAN-2 ,
and modified convert(String data) function,

Changed =>

yield* add(codes[((pattern >> index) & 1) ^ 1], 7);

Replaced to =>

if(index == 0){
   yield* add(codes[pattern < 2 ? 0 : 1], 7);
}
else {
   yield* add(codes[pattern % 2 == 0 ? 0 : 1], 7);
}

In this way, the EAN2 barcode can be generated correctly. 
Please the author also modify the barcode 2.2.4 package, 
and update it to https://pub.dev/packages/barcode .
Let's reference this library directly.
Thanks.

**Comment by DavBfr** [comment]
@shinbin Please create a Pull Request.

**Comment by shinbin** [comment]
@DavBfr Thanks for the guidance, I've created a Pull Request.

**Comment by DavBfr** [comment]
Fixed.
