### ISSUE TITLE
BarcodeException  drawError looks not user frindly 

### ISSUE THREAD

**Issue by kw2019ltd** [DavBfr/dart_barcode#7]
hi
can you enhance below code to display nicer widget instead of below big red container.

from UI prescriptive its looks not nice, or you can add optional error Builder widget inside Barcode Widget where user can give its own widget to display the error or let the user catch the exception and handle it on its own way.

```
on BarcodeException catch (error) {
      FlutterError.reportError(FlutterErrorDetails(
        exception: error,
        library: 'Barcode Widget',
      ));

      assert(() {
        drawError(context, offset, error.message);
        return true;
      }());

```

![image](https://user-images.githubusercontent.com/47334522/82255983-3990fc00-995e-11ea-8aba-5ba4fb12e21c.png)

**Comment by kw2019ltd** [comment]
![image](https://user-images.githubusercontent.com/47334522/82256246-a73d2800-995e-11ea-836e-9d1fe896af6d.png)

**Comment by DavBfr** [comment]
This red message will be displayed only in debug mode, in release build it will simply draw nothing and log the error.

You can check that the barcode is correct ahead of time with `Barcode.verify()` It will throw an exception with an explanation if the barcode cannot be generated.

Check this [example](https://github.com/DavBfr/dart_barcode/blob/788f7106c3160af2a645afc8a90b5e6484250e6f/flutter/example/lib/main.dart#L166).

**Comment by kw2019ltd** [comment]
Sure will try it.

Small q, regarding upce and upca, in case of upce barcode contain 8 digit
somehow i need to convert it to upca that contains 12 digits
If i will not do that iam getting barcode exception.

**Comment by DavBfr** [comment]
Yes, you cannot print anything with UPC E, it's really a compressed representation of UPC A with strict rules.

**Comment by kw2019ltd** [comment]
Yes so if I have upce code how i can show barcode widget do i need to
convert it to upca? And show upca widget?

**Comment by DavBfr** [comment]
we can add a method to convert upce to upca.

**Comment by kw2019ltd** [comment]
Can you do that as part of the plugin?

**Comment by DavBfr** [comment]
There you are, version 1.10.0.
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by kw2019ltd** [comment]
worked like a charm.

what is you bitcoin address

**Comment by DavBfr** [comment]
Here is my address: 1277Vtm81fXmyWt8tmQrGQWzcuofumjGtx

**Comment by kw2019ltd** [comment]
1277Vtm81fXmyWt8tmQrGQWzcuofumjGtx
<https://blockchair.com/bitcoin/address/1277Vtm81fXmyWt8tmQrGQWzcuofumjGtx>
0.00060000 BTCUnspent

done TRX ID:
https://blockchair.com/bitcoin/transaction/3583e4962cd2c209da17eb12dcec6ecfb6348af562128777bf3c999fbd80a255

soon you will get it.

**Comment by DavBfr** [comment]
Thanks!
