### ISSUE TITLE
The imported libraries 'package:barcode_image/barcode_image.dart' and 'package:barcode_widget/barcode_widget.dart' can't have the same name 'barcode_widget'. 

### ISSUE THREAD

**Issue by sgehrman** [DavBfr/dart_barcode#8]
This file is wrong:

https://github.com/DavBfr/dart_barcode/blob/cc36c070fc786bfb33a56cb5df11ec706d5b5efb/image/lib/barcode_image.dart

**Comment by sgehrman** [comment]
https://github.com/DavBfr/dart_barcode/pull/9

**Comment by DavBfr** [comment]
Fixed in barcode_image 1.0.3, thanks.
